In [1]:
# Import tensorflow
import tensorflow as tf
# Import numpy
import numpy as np

## Comparison of tokenization

In [2]:
"It is hard to install Tensorflow on Peter's machine.".split()

['It',
 'is',
 'hard',
 'to',
 'install',
 'Tensorflow',
 'on',
 "Peter's",
 'machine.']

In [3]:
from nltk import word_tokenize

In [4]:
word_tokenize("It is hard to install Tensorflow on Peter's machine .")

## Why there is a difference?

['It',
 'is',
 'hard',
 'to',
 'install',
 'Tensorflow',
 'on',
 'Peter',
 "'s",
 'machine',
 '.']

## Practice of <a href='https://www.tensorflow.org/api_docs/python/tf/constant'>constants</a>

In [14]:
with tf.name_scope('constants'):
    a = tf.constant([-1,1, 1, -1], shape = [2,2], name='a')
    b = tf.constant([0,1], shape = [2,1], name = 'b')
    c = tf.matmul(a, b, name = 'multiply')
print(c)

Tensor("constants_5/multiply:0", shape=(2, 1), dtype=int32)


In [18]:
# Why you cannot get the expected [1, -1]?
# What if we run the matrix multiplication with tf.Session?
with tf.Session() as sess:
    print(sess.run(c))

[[ 1]
 [-1]]


In [19]:
# Generate the computation graph
logs_dir = './computation_graphs'
with tf.Session() as sess:
    log_writer = tf.summary.FileWriter(logs_dir, sess.graph)
    sess.run(c)
log_writer.close()
# run tensorboard --logdir="./computation_graphs" to visualize the computation graph.

In [ ]:
# A1: Compute np.matmul(np.array([[1,2],[3,4],[5,6]]), np.array([[1],[2]]) ) + np.array([1,0,1]) with Tensorflow.

## Practice of <a href='https://www.tensorflow.org/api_docs/python/tf/Variable'>variables</a>


In [20]:
M = tf.Variable(tf.random_normal([3,2], mean=0, stddev=1), name = 'M')
m_times_two = M.assign(M * 2)
init_m = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_m)
    print('M = %s\n' % M.eval())
    sess.run(m_times_two)
    print ('M * 2 = %s\n' %  M.eval())
    sess.run(m_times_two)
    print ('M * 4 = %s\n' % M.eval())

M = [[-0.56148636  1.07881129]
 [-0.24982914  0.34414211]
 [ 0.35811508 -0.44792837]]

M * 2 = [[-1.12297273  2.15762258]
 [-0.49965829  0.68828422]
 [ 0.71623015 -0.89585674]]

M * 4 = [[-2.24594545  4.31524515]
 [-0.99931657  1.37656844]
 [ 1.43246031 -1.79171348]]



In [22]:
# Create a place holder of type float 32-bit.
v = tf.placeholder(tf.float32, shape = [2, 1], name = 'v')
m_times_v = tf.matmul(M, v, name = 'M_v')
with tf.Session() as sess:
    sess.run(init_m)
    print ('M = %s\n' % M.eval())
    print('M * [2,1] = %s \n' % sess.run(m_times_v, {v: [[2],[1]]}))
    print('M * [1,2] = %s \n' % sess.run(m_times_v, {v: [[1],[2]]}))

M = [[ -2.36824839e-04   1.15870059e+00]
 [  3.15839976e-01  -4.49586987e-01]
 [ -2.33650461e-01   2.36535263e+00]]

M * [2,1] = [[ 1.15822697]
 [ 0.18209296]
 [ 1.89805174]] 

M * [1,2] = [[ 2.31716442]
 [-0.58333397]
 [ 4.49705458]] 



In [23]:
# A2: Randomly generate a matrix W and a vector b, compute W * x + b, 
# where x are column vectors from a set of randomly generated vectors.

In [24]:
# Example of word embedding look up.
x = tf.placeholder(tf.int32, shape = [None], name = 'v')
embeddings = tf.Variable(tf.random_uniform([10, 5], -1.0, 1.0), name = 'embed')
embed_seq = tf.nn.embedding_lookup(embeddings, x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('embed = %s\n' % embeddings.eval())
    print('sequence 1 \n')
    print(sess.run(embed_seq, {x: np.array([1,2,3])}))
    print('sequence 2 \n')
    print(sess.run(embed_seq, {x: np.array([1,3])}))

embed = [[ 0.34129     0.94652629  0.29883814  0.11168504 -0.7409482 ]
 [ 0.73556018 -0.9517889  -0.29782343  0.31498504  0.5993371 ]
 [-0.09846258 -0.9983232   0.12924194  0.01870394 -0.78692603]
 [-0.0918684   0.20960116  0.62055922 -0.69075108 -0.04096484]
 [ 0.12929606 -0.81431103  0.75749922 -0.59640956 -0.4910326 ]
 [-0.56342959  0.62118363 -0.85163116 -0.81300521 -0.17812848]
 [-0.40311575  0.25638008 -0.37091923  0.48283458 -0.91451025]
 [ 0.26650858 -0.09428048 -0.36073661 -0.05477262  0.34243298]
 [ 0.42697549 -0.14192176 -0.46312308  0.44191718 -0.06053162]
 [-0.05293417 -0.09861207  0.85404921 -0.72343707 -0.00495124]]

sequence 1 

[[ 0.73556018 -0.9517889  -0.29782343  0.31498504  0.5993371 ]
 [-0.09846258 -0.9983232   0.12924194  0.01870394 -0.78692603]
 [-0.0918684   0.20960116  0.62055922 -0.69075108 -0.04096484]]
sequence 2 

[[ 0.73556018 -0.9517889  -0.29782343  0.31498504  0.5993371 ]
 [-0.0918684   0.20960116  0.62055922 -0.69075108 -0.04096484]]


In [ ]:
## A3: Modify the above code to compute the mean of word embeddings.

## Useful resources:

1. Logistic regression implementation: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/2_BasicModels/logistic_regression.ipynb. Note that it does not follow the best practice.

2. Tensorflow best practices : https://github.com/aicodes/tf-bestpractice

3. Tensorflow course: http://web.stanford.edu/class/cs20si/

4. Best practices for files, folders and models architectures: https://blog.metaflow.fr/tensorflow-a-proposal-of-good-practices-for-files-folders-and-models-architecture-f23171501ae3

5. Code that follows the best practices : https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10.py